{% set name = "wrfplot" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wrfplot-{{ version }}.tar.gz
  sha256: 87641f6875fc1d6330d62ae2538a24c087ed6f593c8530ac1219ff9abc481ebb

build:
  entry_points:
    - wrfplot=wrfplot.wrfplot:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - setuptools
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - cartopy
    - matplotlib-base
    - wrf-python
    - tqdm
    - netcdf4
    - colormaps

test:
  commands:
    # - pip check
    - wrfplot --help
  requires:
    - pip

about:
  home: https://wxguy.in/wrfplot
  summary: Command line application to plot WRF model output data
  dev_url: https://github.com/wxguy/wrfplot
  doc_url: https://wxguy.in/wrfplot
  license: GPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - wxguy
