{% set name = "wrfplot" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wrfplot-{{ version }}.tar.gz
  sha256: 11e84b292a01e5d8f5c3bd5098371c85b45b870ff0f769f3c21eaf54658af629

build:
  entry_points:
    - wrfplot=wrfplot.wrfplot:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - setuptools
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - cartopy
    - matplotlib-base <3.6
    - wrf-python >=1.3
    - tqdm
    - netcdf4
    - colormaps

test:
  commands:
    # - pip check
    - wrfplot --help
  requires:
    - pip

about:
  home: https://github.com/wxguy/wrfplot
  summary: Command line application to plot WRF model output data
  dev_url: https://github.com/wxguy/wrfplot/
  license: GPL-3.0 AND GPL-1.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - wxguy
