{% set name = "wrfplot" %}
{% set version = "0.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wrfplot-{{ version }}.tar.gz
  sha256: 2f06e34ac76093e264ff0fa357c568ca6ee2ae198fe10de174c2a058aafc882a

build:
  entry_points:
    - wrfplot=wrfplot.wrfplot:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - setuptools
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - cartopy
    - matplotlib-base <3.6
    - wrf-python >=1.3
    - imageio
    - tqdm
    - netcdf4

test:
  commands:
    # - pip check
    - wrfplot --help
  requires:
    - pip

about:
  home: https://github.com/wxguy/wrfplot
  summary: Command line application to plot WRF model output data
  dev_url: https://github.com/wxguy/wrfplot/
  license: GPL-3.0 AND GPL-1.0-or-later
  license_file:
    - LICENSE
    - wrfplot/colormaps/colormaps/ncar_ncl/Copyright

extra:
  recipe-maintainers:
    - wxguy
